"""Discrete-measure contract for Mobile V2 shared-face transport.

The numerical fluxes used by Mobile V2 are fluxes *per unit face length*.
For a face of length ``L`` and substep ``dt``, one shared integrated transfer
is therefore ``flux * L * dt``.  Vertex state variables remain depths and
depth-integrated momenta, so each endpoint divides that transfer by its own
Triangle-A-C dual control area.

This small NumPy helper is the executable algebraic contract used by the
canonical CPU tests.  Production execution mirrors it in the Warp kernel.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass(frozen=True)
class SharedFaceIncrement:
    """Endpoint increments generated by one authoritative face transfer."""

    delta_h_i_m: float
    delta_h_j_m: float
    delta_q_i_m2_s: np.ndarray
    delta_q_j_m2_s: np.ndarray
    transferred_volume_m3: float
    transferred_momentum_measure_m4_s: np.ndarray


def shared_face_increment(
    *,
    mass_flux_m2_s: float,
    momentum_flux_m3_s2: np.ndarray,
    face_length_m: float,
    dt_s: float,
    area_i_m2: float,
    area_j_m2: float,
) -> SharedFaceIncrement:
    """Return weight-aware increments for an oriented internal face ``i -> j``.

    A positive flux removes material/momentum measure from ``i`` and adds the
    exact same integrated transfer to ``j``.  There is deliberately no
    one-sided re-evaluation, correction pass, or uniform-area assumption.
    """

    if face_length_m <= 0.0 or dt_s < 0.0:
        raise ValueError("face_length_m must be positive and dt_s non-negative")
    if area_i_m2 <= 0.0 or area_j_m2 <= 0.0:
        raise ValueError("dual control areas must be positive")
    momentum_flux = np.asarray(momentum_flux_m3_s2, dtype=np.float64)
    if momentum_flux.shape != (2,):
        raise ValueError("momentum_flux_m3_s2 must contain x/y components")
    volume = float(mass_flux_m2_s) * float(face_length_m) * float(dt_s)
    momentum = momentum_flux * float(face_length_m) * float(dt_s)
    return SharedFaceIncrement(
        delta_h_i_m=-volume / float(area_i_m2),
        delta_h_j_m=volume / float(area_j_m2),
        delta_q_i_m2_s=-momentum / float(area_i_m2),
        delta_q_j_m2_s=momentum / float(area_j_m2),
        transferred_volume_m3=volume,
        transferred_momentum_measure_m4_s=momentum,
    )


def authoritative_mobile_volume_m3(h_m: np.ndarray, area_m2: np.ndarray) -> float:
    """The sole physical Mobile-volume definition used by the repair."""

    return float(
        np.sum(
            np.asarray(h_m, dtype=np.float64)
            * np.asarray(area_m2, dtype=np.float64),
            dtype=np.float64,
        )
    )


def authoritative_mobile_momentum_measure_m4_s(
    q_m2_s: np.ndarray, area_m2: np.ndarray
) -> np.ndarray:
    """Return ``sum(A_i q_i)`` before multiplication by bulk density."""

    q = np.asarray(q_m2_s, dtype=np.float64)
    area = np.asarray(area_m2, dtype=np.float64)
    if q.shape != area.shape + (2,):
        raise ValueError("q_m2_s must have shape area_m2.shape + (2,)")
    return np.sum(q * area[..., None], axis=(0, 1), dtype=np.float64)
